### ISSUE TITLE
Log to a central file, not the terminal.

### ISSUE THREAD

**Issue by MobiusHorizons** [MobiusHorizons/syncd#9]
Implement a logging service that everything can go through. On Build, the `DEBUG` environment variable, or the `--verbose` flag at run will toggle the level of logging.

**Comment by yjftsjthsd-g** [comment]
Clarification: What does the logging service do? Are we just accumulating messages from plugins? Dumping to a log file? (The latter has solutions for system-wide daemons, but it looks like user programs end up using ~/.config/*/*.log files)

**Comment by MobiusHorizons** [comment]
Primarily I meant that we would provide a function that we could use instead of printf, which could decide to mute output.

**Comment by yjftsjthsd-g** [comment]
src/log.[ch] in logging branch addresses this
